### ISSUE TITLE
error: operation 'addTempRoot' is not supported by store

### ISSUE THREAD

**Issue by CorbanR** [NixOS/nix#4303]
**Describe the bug**

Having issues with `nix copy --to "file:///$PWD/_output/cache?compression=xz"` command in github actions.

**Steps To Reproduce**
I've tried reproducing the behavior on my local mac, and on a linux machine (via docker), this appears to only be an issue when running inside github actions 

Example Action
```
jobs:
  tests-and-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15]
    steps:
      # v2.3.4
    - uses: actions/checkout@5a4ac9002d

      # v12
    - uses: cachix/install-nix-action@07da2520ee
      with:
        nix_path: nixpkgs=channel:nixpkgs-unstable

    - name: Build tests
      run: nix-build --max-jobs 2 --cores 2 tests.nix

    - name: Cleanup test results
      run: rm -rf results*

    - name: Create output path
      run: mkdir -p _output/cache

      # We only need to do this particular step once
    - name: Create channel archive
      if: startsWith(matrix.os,'ubuntu')
      run: |
        tar -cJf "_output/nixexprs.tar.xz" ./*.nix pkgs/ maintainers/ \
            --transform "s,^,${PWD##*/}/," \
            --owner=0 --group=0 --mtime="1970-01-01 00:00:00 UTC"

        touch "_output/index.html"
        printf 'https://nixpkgs.raunco.co/cache' > "_output/binary-cache-url"

    - name: Build the packages
      run: nix-build --max-jobs 2 --cores 2

    - name: optimize nix-store to reduce size
      run: nix-store --optimise

    - name: Sign the packages
      if: (github.event_name == 'push' || github.event.inputs.deploy == 'true') && github.ref == 'refs/heads/master'
      run: |
        export NIX_SECRET_KEY_FILE="$PWD/nix-cache-priv-key.pem"
        echo "$NIX_SECRET_KEY" > "$NIX_SECRET_KEY_FILE"
        nix sign-paths -k "$NIX_SECRET_KEY_FILE"
        rm -rf "$NIX_SECRET_KEY_FILE"
      env:
        NIX_SECRET_KEY: ${{ secrets.NIX_SECRET_KEY }}

    # THIS is the step that is now failing.
    - name: nix copy to file
      run: |
        nix copy --to "file:///$PWD/_output/cache?compression=xz"
        nix path-info --store "file:///$PWD/_output/cache" --json | json_pp
```
**Expected behavior**
I would expect the `nix copy --to ` to work without error.

**`nix-env --version` output**
```
nix-env (Nix) 2.3.9
```
**Additional context**

This was previously working for me, and recently upgraded the actions. I opened up ticket https://github.com/cachix/install-nix-action/issues/60 , but it doesn't seem to be an issue specifically with this action.

I found ticket https://github.com/NixOS/nix/issues/2637 as well, and while similar,  I don't think it's quite the same issue

Example of failed job https://github.com/CorbanR/nixpkgs/runs/1488192369?check_suite_focus=true

Any advice or additional things to try would be greatly appreciated.
