### ISSUE TITLE
Nix 2.3.11 broke substituting big nars

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nix#4832]
```
unable to download 'https://xxx.cachix.org/nar/35f54c17e3f4d48433fc008ec5aebf0a2efdd7657c97f9b94cff09d344197f43.nar.xz': HTTP error 200 (curl error: Transferred a partial file)
error: build of '/nix/store/k7jj127qg6kwcs4l8vjx0v1mdjcmr91j-python3.8-pytorch-1.8.1' failed
```

Reverting to Nix 2.3.11 makes things work again:

```yaml
- uses: cachix/install-nix-action@v13
    with:
      install_url: https://releases.nixos.org/nix/nix-2.3.10/install
```
