### ISSUE TITLE
Stricter compilation settings in local dev

### ISSUE THREAD

**Issue by roberth** [NixOS/nix#8625]
**Is your feature request related to a problem? Please describe.**

We have issues that can be caught be compilers.
 - #8617 
 - probably more

We want to catch these mistakes in a local build during development, and we also want to catch them in CI

We do not want to fail the _package_ build when the issue is insignificant, such as a warning. Otherwise build success will be too sensitive to compiler updates and such that users may want to apply through input overriding, and we'd make life unnecessarily hard on distributions such as Nixpkgs.

**Describe the solution you'd like**

A pedantic attribute in the derivation, so that the derived dev shell can enable that. When the pedantic flag is set, the configure script picks that up and sets a bunch of flags that make the compiler check for various things and fail if those checks are violated.

**Describe alternatives you've considered**

**Additional context**

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by inclyc** [comment]
The clangd language server reads `.clangd` file for customization flags, including `-Wxxx` && `.clang-tidy` provides more static analysis. Might be a simple solution that does not need to change current building system (it actually works fine). Shall we make these checks mandatory?

Related: #6721

**Comment by inclyc** [comment]
The flake provided by this repository offers a devShell that includes clangd. My `.envrc`:

```sh
use flake .#native-clangStdenvPackages
```

It was introduced in https://github.com/NixOS/nix/pull/7433, and works perfect for me.

> but it doesn't seem to have been packaged

The pname is `clang-tools` in nixpkgs.

**Comment by roberth** [comment]
Thanks! I'd been using https://github.com/microsoft/vscode-cpptools until now, and I was unaware of #7433 somehow. `clangd` wasn't listed on search.nixos.org when I checked yesterday, but it is today :thinking: 
I've switched just now and I'm curious which setup takes more effort to maintain.

**Comment by inclyc** [comment]
> I've switched just now and I'm curious which setup takes more effort to maintain.

Clangd gives us more accurate warning & language hints. But requires the compilation database `compile_commands.json` and some customization flags. ms-cpptools might work out of box for normal projects. I would like prefer clangd because it gives me more information on this code base.

![Screenshot_20230706_170222](https://github.com/NixOS/nix/assets/36667224/acbce814-8f26-4383-9a90-bb1b40822d30)


clangd also provides uniform range-based auto-formatting, I'm submitting PRs formatted by `.clang-format` cherry-picked from #6721:

```yaml
BasedOnStyle: LLVM
IndentWidth: 4
BreakBeforeBraces: Custom
BraceWrapping:
  AfterStruct: true
  AfterClass: true
  AfterFunction: true
  AfterUnion: true
  SplitEmptyRecord: false
PointerAlignment: Middle
FixNamespaceComments: false
SortIncludes: Never
#IndentPPDirectives: BeforeHash
SpaceAfterCStyleCast: true
SpaceAfterTemplateKeyword: false
AccessModifierOffset: -4
AlignAfterOpenBracket: AlwaysBreak
AlignEscapedNewlines: DontAlign
ColumnLimit: 120
BreakStringLiterals: false
BitFieldColonSpacing: None
AllowShortFunctionsOnASingleLine: Empty
AlwaysBreakTemplateDeclarations: Yes
BinPackParameters: false
BreakConstructorInitializers: BeforeComma
EmptyLineAfterAccessModifier: Leave # change to always/never later?
EmptyLineBeforeAccessModifier: Leave
#PackConstructorInitializers: BinPack
BreakBeforeBinaryOperators: NonAssignment
AlwaysBreakBeforeMultilineStrings: true
```

The hacking guide described how to setup clangd correctly for nix: https://nixos.org/manual/nix/unstable/contributing/hacking.html#editor-integration
