### ISSUE TITLE
streamingProcess: runInteractiveProcess: exec: does not exist

### ISSUE THREAD

**Issue by Pitometsu** [NixOS/nix#944]
Stack can't resolve dependencies. Not sure, is it nix issue. Anyway, I use Nix, so it could be a case of integration.

``` shell
$ stack build
No packages found in snapshot which provide a "hsc2hs" executable, which is a build-tool dependency of "skein"
Missing build-tools may be caused by dependencies of the build-tool being overridden by extra-deps.
This should be fixed soon - see this issue https://github.com/commercialhaskell/stack/issues/595

No packages found in snapshot which provide a "hsc2hs" executable, which is a build-tool dependency of "postgresql-libpq"
Missing build-tools may be caused by dependencies of the build-tool being overridden by extra-deps.
This should be fixed soon - see this issue https://github.com/commercialhaskell/stack/issues/595

clock-0.5.1: configure
aeson-0.11.1.4: configure
adjunctions-4.3: configure
case-insensitive-1.2.0.6: configure
blaze-builder-0.4.0.2: configure
crypto-random-0.0.9: configure
crypto-cipher-types-0.0.9: configure
double-conversion-2.0.1.0: configure
Progress: 8/57/home/netsu/.stack/setup-exe-cache/x86_64-linux/setup-Simple-Cabal-1.22.5.0-ghc-7.10.3: streamingProcess: runInteractiveProcess: exec: does not exist (No such file or directory)

/home/netsu/.stack/setup-exe-cache/x86_64-linux/setup-Simple-Cabal-1.22.5.0-ghc-7.10.3: streamingProcess: runInteractiveProcess: exec: does not exist (No such file or directory)

/home/netsu/.stack/setup-exe-cache/x86_64-linux/setup-Simple-Cabal-1.22.5.0-ghc-7.10.3: streamingProcess: runInteractiveProcess: exec: does not exist (No such file or directory)

/home/netsu/.stack/setup-exe-cache/x86_64-linux/setup-Simple-Cabal-1.22.5.0-ghc-7.10.3: streamingProcess: runInteractiveProcess: exec: does not exist (No such file or directory)

/home/netsu/.stack/setup-exe-cache/x86_64-linux/setup-Simple-Cabal-1.22.5.0-ghc-7.10.3: streamingProcess: runInteractiveProcess: exec: does not exist (No such file or directory)

/home/netsu/.stack/setup-exe-cache/x86_64-linux/setup-Simple-Cabal-1.22.5.0-ghc-7.10.3: streamingProcess: runInteractiveProcess: exec: does not exist (No such file or directory)

/home/netsu/.stack/setup-exe-cache/x86_64-linux/setup-Simple-Cabal-1.22.5.0-ghc-7.10.3: streamingProcess: runInteractiveProcess: exec: does not exist (No such file or directory)

/home/netsu/.stack/setup-exe-cache/x86_64-linux/setup-Simple-Cabal-1.22.5.0-ghc-7.10.3: streamingProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
```

``` shell
$ stack --version
Version 1.1.2 x86_64 hpack-0.14.1
```

Same for stack 1.1.3 from git.

``` shell
$ nix-build --version
nix-build (Nix) 1.11.2
```

``` yaml
$ cat stack.yaml 
flags: {}
nix:
  enable: true
  shell-file: shell_stack.nix
extra-package-dbs: []
ghc-options:
  ! '*': -ghci-script .ghci_conf
packages:
- '.'
- location:
    git: https://github.com/snapframework/heist.git
    commit: 829fc6133d328de8e7af1675832e42658c5da387
  extra-dep: true
- location:
    git: https://github.com/snapframework/io-streams-haproxy.git
    commit: ab208d49fe73c9cf05e46c0d929eec311fb0cfd9
  extra-dep: true
- location:
    git: https://github.com/snapframework/snap-server.git
    commit: f2c4ced4f3414a3a2e7eaf422c5002a8decb2512
  extra-dep: true
- location:
    git: https://github.com/snapframework/snap-core.git
    commit: 64e25f72d7e3375145b4a77e5c2da288aa821922
  extra-dep: true
- location:
    git: https://github.com/snapframework/snap.git
    commit: bb45b70ec1234bef4b193c1daa617a8134fe829e
  extra-dep: true
- location:
    git: https://github.com/snapframework/snap-loader-static.git
    commit: 4df25f78d96a4cecab747452001a8f7523be9b77
- location:
    git: https://github.com/snapframework/snap-loader-dynamic
    commit: 32680dc0b8f65eecefacfbb17e35df61f7fe3a7d
- location:
    git: https://github.com/haskell-servant/servant.git
    commit: c2c9bef5715bdfb1819f54e00127a62f2fdc44ec
  subdirs:
  - servant
  - servant-blaze
  extra-dep: true
( . . . )
- location:
    git: https://github.com/dbp/hspec-snap.git
    commit: a09c22cd49affbd883236ffb13643642869c6863
  extra-dep: true
extra-deps:
- aeson-0.11.1.4
- clock-0.5.1
- heist-1.0.0.0
- hspec-snap-1.0.0.0
- servant-0.6.1
- servant-blaze-0.6.1
- snap-1.0.0.0
- snap-core-1.0.0.0
- snap-server-1.0.0.0
rebuild-ghc-options: true
compiler-check: newer-minor
compiler: ghc-7.10.3
resolver: lts-5.15
require-stack-version: ! '>= 1.1.2'
```

``` nix
$ cat shell_stack.nix
# only works with Stack >= 1.1.3, with stack-1.1.2 will use lts-5.15
{ nixpkgs ? import <nixpkgs> { config.allowUnfree = true; }
, ghc_lts ? nixpkgs.haskell.packages.lts-5_15 }:

with nixpkgs;
with haskell.lib;

let
  ghc_stack = ghc_lts.override rec {
    overrides = self: super: {
      # fix hoogle dependency in lts-5_15
      vector-algorithms = overrideCabal super.vector-algorithms (drv: {
        libraryHaskellDepends = with self; [ mtl mwc-random ] ++ drv.libraryHaskellDepends;
      });
      # fix dependencies not resolved by stack # <-- fix bug with stack-1.1.3
      # pipes-transduce = super.pipes-transduce.override {
      #   foldl = self.foldl_1_2_1;
      # };
      # foldl_1_2_1 = overrideCabal super.foldl (drv: {
      #   version = "1.2.1";
      #   sha256 = "0ww0wsv3b11qgpjzj3nlixz5gwy65yhpy40pww0rj7crh7gsibw6";
      # });
    };
  };
in with ghc_stack;

haskell.lib.buildStackProject {
  name = "stackDevEnv";
  buildInputs = with nixpkgs; [ bash git postgresql95 zlib gcc
    pkgconfig openssl cacert # nixpkgs.stack # <-- tried stack with --no-nix in nix-shell
    cabal-install # hsc2hs process-streaming # <-- Do not help to solve issue
  ];
  ghc = (ghcWithHoogle (hpkgs: [
    hlint
    hi
    (dontCheck intero)
    funnyprint
    haskell-docs
    stylish-haskell
    structured-haskell-mode
    ghc-mod
    hasktags
    HaRe
  ]));
  shellHook = ''
    export GIT_SSL_CAINFO='/etc/ssl/certs/ca-certificates.crt'
  '';
}
```
